import { locales, type Locale } from './i18n.ts';
import { localizeRows } from './localized-rows.ts';

const fields = [
  'title',
  'intro',
  'languageLabel',
  'network',
  'health',
  'riskSummary',
  'markets',
  'positions',
  'symbol',
  'side',
  'size',
  'entry',
  'mark',
  'notional',
  'adverseMove',
  'portfolioDrawdown',
  'liquidationDistance',
  'maintenanceMargin',
  'fundingDirection',
  'unavailableUnproven',
  'sourceQuality',
  'inspectSource',
  'readOnly',
  'noObservation',
  'noPositions',
  'apiLinks',
  'fixtureNotice',
  'provenanceTitle',
  'snapshotLabel',
  'observedLabel',
  'sourceHashes',
  'unknownSourceHash',
  'quality',
  'received',
  'sequence',
  'contentHash',
] as const;

const statusCodes = [
  'AVAILABLE',
  'NO_ACCOUNT',
  'NO_POSITION',
  'STALE',
  'UNAVAILABLE',
  'HEALTHY',
  'DEGRADED',
  'UNKNOWN',
] as const;

const fieldsByLocale = localizeRows(fields, {
  en: [
    'Risk and market observation',
    'Read-only Perpl observations and deterministic risk snapshots. NERVA cannot place orders or move funds.',
    'Language',
    'Network',
    'Provider health',
    'Risk snapshot',
    'Markets',
    'Open positions',
    'Market',
    'Side',
    'Size',
    'Entry',
    'Mark',
    'Notional',
    'Adverse move',
    'Day portfolio drawdown',
    'Liquidation distance',
    'Maintenance margin',
    'Funding direction',
    'UNAVAILABLE_UNPROVEN',
    'Source quality',
    'Inspect source',
    'READ ONLY · EXECUTION DISABLED',
    'No provider observations have been stored yet.',
    'No open positions in the latest available account snapshot.',
    'Read-only APIs',
    'Fixture or demo mode is active. This data is not live.',
    'Risk provenance and freshness',
    'Snapshot',
    'observed',
    'Source snapshot hashes',
    'no verifiable source hash',
    'Quality',
    'Received',
    'Sequence',
    'Content hash',
  ],
  'pt-BR': [
    'Observação de risco e mercado',
    'Observações Perpl somente para leitura e snapshots determinísticos de risco. O NERVA não envia ordens nem movimenta fundos.',
    'Idioma',
    'Rede',
    'Saúde dos provedores',
    'Snapshot de risco',
    'Mercados',
    'Posições abertas',
    'Mercado',
    'Lado',
    'Tamanho',
    'Entrada',
    'Marcação',
    'Exposição',
    'Movimento adverso',
    'Drawdown diário da carteira',
    'Distância de liquidação',
    'Margem de manutenção',
    'Direção do funding',
    'UNAVAILABLE_UNPROVEN',
    'Qualidade da fonte',
    'Inspecionar fonte',
    'SOMENTE LEITURA · EXECUÇÃO DESABILITADA',
    'Ainda não há observações de provedores armazenadas.',
    'Nenhuma posição aberta no snapshot de conta disponível mais recente.',
    'APIs somente leitura',
    'O modo de fixture ou demonstração está ativo. Estes dados não são ao vivo.',
    'Origem e atualidade do risco',
    'Snapshot',
    'observado',
    'Hashes dos snapshots de origem',
    'sem hash de origem verificável',
    'Qualidade',
    'Recebido',
    'Sequência',
    'Hash do conteúdo',
  ],
  es: [
    'Observación de riesgo y mercado',
    'Observaciones Perpl de solo lectura y snapshots deterministas de riesgo. NERVA no envía órdenes ni mueve fondos.',
    'Idioma',
    'Red',
    'Salud de proveedores',
    'Snapshot de riesgo',
    'Mercados',
    'Posiciones abiertas',
    'Mercado',
    'Lado',
    'Tamaño',
    'Entrada',
    'Marca',
    'Exposición',
    'Movimiento adverso',
    'Drawdown diario de cartera',
    'Distancia de liquidación',
    'Margen de mantenimiento',
    'Dirección del funding',
    'UNAVAILABLE_UNPROVEN',
    'Calidad de la fuente',
    'Inspeccionar fuente',
    'SOLO LECTURA · EJECUCIÓN DESHABILITADA',
    'Todavía no hay observaciones de proveedores almacenadas.',
    'No hay posiciones abiertas en el snapshot de cuenta disponible más reciente.',
    'APIs de solo lectura',
    'El modo de fixture o demostración está activo. Estos datos no son en vivo.',
    'Origen y vigencia del riesgo',
    'Snapshot',
    'observado',
    'Hashes de snapshots de origen',
    'sin hash de origen verificable',
    'Calidad',
    'Recibido',
    'Secuencia',
    'Hash del contenido',
  ],
});

const statusesByLocale = localizeRows(statusCodes, {
  en: [
    'Available',
    'No account',
    'No position',
    'Stale',
    'Unavailable',
    'Healthy',
    'Degraded',
    'Unknown',
  ],
  'pt-BR': [
    'Disponível',
    'Sem conta',
    'Sem posição',
    'Desatualizado',
    'Indisponível',
    'Saudável',
    'Degradado',
    'Desconhecido',
  ],
  es: [
    'Disponible',
    'Sin cuenta',
    'Sin posición',
    'Desactualizado',
    'No disponible',
    'Saludable',
    'Degradado',
    'Desconocido',
  ],
});

type DashboardCopy = (typeof fieldsByLocale)['en'] & {
  readonly status: Readonly<Record<(typeof statusCodes)[number], string>>;
};

export const dashboardCopy = Object.fromEntries(
  locales.map((locale) => [
    locale,
    { ...fieldsByLocale[locale], status: statusesByLocale[locale] },
  ]),
) as Record<Locale, DashboardCopy>;
