import { GUIDED_PHASES, type DemoScenarioId } from './demo-model.ts';
import { localizeRows } from '../localized-rows.ts';

const copyKeys = [
  'label',
  'title',
  'intro',
  'warning',
  'guided',
  'start',
  'next',
  'reset',
  'phase',
  'elapsed',
  'seconds',
  'scenarios',
  'context',
  'risk',
  'policy',
  'deterioration',
  'safety',
  'outcome',
  'evidence',
  'closeout',
  'refusal',
  'staleReason',
  'revokedReason',
  'delegateReason',
  'degradedReason',
  'source',
  'riskEvidence',
  'policyVersion',
  'trigger',
  'plan',
  'simulation',
  'permission',
  'decision',
  'monitor',
  'mode',
  'local',
  'riskLabel',
  'exposure',
  'exposureValue',
  'unproven',
  'permissionSummary',
  'authority',
  'policyBuilder',
  'policyHint',
  'emergency',
  'emergencyState',
  'killSwitch',
  'recorder',
  'traceState',
  'nonAuthoritative',
  'home',
  'dashboard',
  'policies',
  'permissions',
  'flightRecorder',
  'liveLabel',
  'skipContent',
  'primaryNav',
  'languageLabel',
  'inProgress',
  'untrustedRequest',
  'policyPlaceholder',
  'policyFinePrint',
  'scenarioRefused',
  'scenarioSynthetic',
  'observedSynthetic',
  'pending',
  'experienceEyebrow',
  'walkthroughEyebrow',
  'safetyEyebrow',
  'trustViewEyebrow',
  'demoOnlyTag',
  'noAuthorityTag',
  'draftOnlyTag',
  'localFixtureEyebrow',
  'demoTraceLocal',
  'simulatedOutcome',
] as const;

export const demoCopy = localizeRows(copyKeys, {
  en: [
    'DEMO ONLY · SYNTHETIC DATA',
    'Protection you can inspect.',
    'A deterministic walkthrough of risk, bounded authority, refusal and evidence.',
    'Nothing here is connected to a wallet, provider, database or financial effect.',
    '84-second guided demo',
    'Start guided demo',
    'Advance one phase',
    'Reset demo',
    'Phase',
    'Scripted time',
    'seconds',
    'Safety scenarios',
    'Monad Testnet · Perpl perpetuals',
    'Risk is deterministic and sourced. Unproven liquidation distance stays unavailable.',
    'Policy preview · REDUCE_POSITION only · 10% maximum · NO_ACTION fallback',
    'Synthetic adverse move crosses the example trigger. Fixture only.',
    'Preflight checks freshness, provider health, permission and delegation before any path.',
    'SIMULATED OUTCOME · DRY_RUN_ONLY · no provider receipt or transaction exists.',
    'Local synthetic trace · not cryptographic evidence and not stored.',
    'End state · effects remain blocked, the demo can be reset, and M06 is not part of this walkthrough.',
    'REFUSED · no action is proposed because a required safety condition failed.',
    'Source is stale. Current data cannot authorize a decision.',
    'The parent permission is revoked. Derived authority is invalid.',
    'Delegation changed. Authority bound to the prior observation is invalid.',
    'Provider health is degraded. The path is non-actionable.',
    'Source snapshot',
    'Deterministic risk',
    'Policy version',
    'Trigger evaluation',
    'Bounded plan',
    'Simulation / preflight',
    'Permission check',
    'Decision / outcome',
    'Protection monitor',
    'Mode',
    'Local-only deterministic state',
    'Risk context',
    'Example exposure',
    '$12,400 synthetic',
    'LIQUIDATION_DISTANCE · UNAVAILABLE_UNPROVEN',
    'Authority summary',
    'Bounded example · expires in 20 minutes · revocation wins',
    'Policy builder preview',
    'Templates and natural-language text stay untrusted until the existing review path confirms them.',
    'Emergency and safety',
    'Mainnet effect: HARD_BLOCKED · Live Perpl writes: BLOCKED',
    'SYNTHETIC KILL SWITCH · ON · demo cannot change controls',
    'Flight Recorder lineage',
    'DEMO TRACE · synthetic and local; not provider evidence.',
    'STALE, UNKNOWN and unproven metrics never become authority.',
    'Home',
    'Risk dashboard',
    'Policies',
    'Permissions',
    'Flight Recorder',
    'Live product views are separately labeled LIVE READ ONLY.',
    'Skip to content',
    'Primary navigation',
    'Language',
    'Demo in progress…',
    'Untrusted request draft',
    'Example: reduce the position if daily drawdown crosses a limit…',
    'Text is not sent to or interpreted by an LLM. Use /policies to validate a structured template.',
    'REFUSED · NO ACTION',
    'SYNTHETIC · DRY RUN',
    'OBSERVED · SYNTHETIC',
    'PENDING',
    'M05 · EXPERIENCE PREVIEW',
    'GUIDED WALKTHROUGH',
    'FAIL-CLOSED BY DESIGN',
    'READ-ONLY TRUST VIEW',
    'DEMO ONLY',
    'NO AUTHORITY',
    'DRAFT ONLY',
    'LOCAL FIXTURE LINEAGE',
    'DEMO TRACE · LOCAL',
    'SIMULATED OUTCOME',
  ],
  'pt-BR': [
    'SOMENTE DEMO · DADOS SINTÉTICOS',
    'Proteção que você pode inspecionar.',
    'Um percurso determinístico por risco, autoridade limitada, recusa e evidências.',
    'Nada aqui se conecta a carteira, provedor, banco de dados ou efeito financeiro.',
    'Demo guiada de 84 segundos',
    'Iniciar demo guiada',
    'Avançar uma etapa',
    'Reiniciar demo',
    'Etapa',
    'Tempo roteirizado',
    'segundos',
    'Cenários de segurança',
    'Monad Testnet · Perpétuos Perpl',
    'O risco é determinístico e tem origem explícita. Distância de liquidação não comprovada continua indisponível.',
    'Prévia de política · somente REDUCE_POSITION · máximo 10% · fallback NO_ACTION',
    'Movimento adverso sintético cruza o gatilho de exemplo. Apenas fixture.',
    'O preflight verifica atualidade, saúde do provedor, permissão e delegação antes de qualquer caminho.',
    'RESULTADO SIMULADO · DRY_RUN_ONLY · não existe recibo de provedor nem transação.',
    'Trilha sintética local · não é evidência criptográfica e não foi persistida.',
    'Estado final · efeitos continuam bloqueados, a demo pode ser reiniciada e M06 não faz parte deste percurso.',
    'RECUSADO · nenhuma ação é proposta porque uma condição de segurança falhou.',
    'A fonte está desatualizada. Dados atuais não podem autorizar uma decisão.',
    'A permissão principal foi revogada. A autoridade derivada é inválida.',
    'A delegação mudou. A autoridade vinculada à observação anterior é inválida.',
    'A saúde do provedor está degradada. O caminho não permite ação.',
    'Snapshot de origem',
    'Risco determinístico',
    'Versão da política',
    'Avaliação do gatilho',
    'Plano limitado',
    'Simulação / preflight',
    'Verificação de permissão',
    'Decisão / resultado',
    'Monitor de proteção',
    'Modo',
    'Estado determinístico somente local',
    'Contexto de risco',
    'Exposição de exemplo',
    'US$ 12.400 sintéticos',
    'LIQUIDATION_DISTANCE · UNAVAILABLE_UNPROVEN',
    'Resumo de autoridade',
    'Exemplo limitado · expira em 20 minutos · revogação prevalece',
    'Prévia do construtor de políticas',
    'Modelos e texto em linguagem natural permanecem não confiáveis até confirmação pelo fluxo de revisão existente.',
    'Emergência e segurança',
    'Efeito em mainnet: HARD_BLOCKED · Escritas Perpl ao vivo: BLOCKED',
    'KILL SWITCH SINTÉTICO · ON · a demo não altera controles',
    'Linhagem do Flight Recorder',
    'TRILHA DEMO · sintética e local; não é evidência de provedor.',
    'STALE, UNKNOWN e métricas não comprovadas nunca se tornam autoridade.',
    'Início',
    'Painel de risco',
    'Políticas',
    'Permissões',
    'Flight Recorder',
    'As telas do produto ao vivo têm o rótulo separado LIVE READ ONLY.',
    'Pular para o conteúdo',
    'Navegação principal',
    'Idioma',
    'Demo em andamento…',
    'Rascunho de solicitação não confiável',
    'Ex.: reduza a posição se a perda diária exceder o limite…',
    'Texto não enviado nem interpretado por LLM. Use /policies para validar um modelo estruturado.',
    'RECUSADO · SEM AÇÃO',
    'SINTÉTICO · SIMULAÇÃO',
    'OBSERVADO · SINTÉTICO',
    'PENDENTE',
    'M05 · PRÉVIA DA EXPERIÊNCIA',
    'PERCURSO GUIADO',
    'SEGURANÇA FAIL-CLOSED',
    'VISÃO DE CONFIANÇA SOMENTE LEITURA',
    'SOMENTE DEMO',
    'SEM AUTORIDADE',
    'SOMENTE RASCUNHO',
    'LINHAGEM LOCAL DA FIXTURE',
    'TRILHA DEMO · LOCAL',
    'RESULTADO SIMULADO',
  ],
  es: [
    'SOLO DEMO · DATOS SINTÉTICOS',
    'Protección que puedes inspeccionar.',
    'Un recorrido determinista por riesgo, autoridad limitada, rechazo y evidencia.',
    'Nada aquí se conecta a una cartera, proveedor, base de datos o efecto financiero.',
    'Demo guiada de 84 segundos',
    'Iniciar demo guiada',
    'Avanzar una fase',
    'Reiniciar demo',
    'Fase',
    'Tiempo guionizado',
    'segundos',
    'Escenarios de seguridad',
    'Monad Testnet · Perpetuos de Perpl',
    'El riesgo es determinista y tiene origen explícito. La distancia de liquidación no probada sigue no disponible.',
    'Vista previa de política · solo REDUCE_POSITION · máximo 10% · fallback NO_ACTION',
    'Movimiento adverso sintético supera el disparador de ejemplo. Solo fixture.',
    'El preflight comprueba vigencia, salud del proveedor, permiso y delegación antes de cualquier ruta.',
    'RESULTADO SIMULADO · DRY_RUN_ONLY · no existe recibo del proveedor ni transacción.',
    'Traza sintética local · no es evidencia criptográfica y no se almacenó.',
    'Estado final · los efectos siguen bloqueados, la demo se puede reiniciar y M06 no forma parte de este recorrido.',
    'RECHAZADO · no se propone ninguna acción porque falló una condición de seguridad.',
    'La fuente está desactualizada. Los datos actuales no pueden autorizar una decisión.',
    'El permiso principal fue revocado. La autoridad derivada no es válida.',
    'La delegación cambió. La autoridad vinculada a la observación anterior no es válida.',
    'La salud del proveedor está degradada. La ruta no permite acciones.',
    'Snapshot de origen',
    'Riesgo determinista',
    'Versión de política',
    'Evaluación del disparador',
    'Plan limitado',
    'Simulación / preflight',
    'Comprobación de permiso',
    'Decisión / resultado',
    'Monitor de protección',
    'Modo',
    'Estado determinista solo local',
    'Contexto de riesgo',
    'Exposición de ejemplo',
    '12.400 USD sintéticos',
    'LIQUIDATION_DISTANCE · UNAVAILABLE_UNPROVEN',
    'Resumen de autoridad',
    'Ejemplo limitado · vence en 20 minutos · prevalece la revocación',
    'Vista previa del constructor de políticas',
    'Las plantillas y el texto natural siguen sin confianza hasta la confirmación por el flujo de revisión existente.',
    'Emergencia y seguridad',
    'Efecto en mainnet: HARD_BLOCKED · Escrituras Perpl en vivo: BLOCKED',
    'KILL SWITCH SINTÉTICO · ON · la demo no cambia controles',
    'Linaje de Flight Recorder',
    'TRAZA DEMO · sintética y local; no es evidencia del proveedor.',
    'STALE, UNKNOWN y las métricas no probadas nunca se convierten en autoridad.',
    'Inicio',
    'Panel de riesgo',
    'Políticas',
    'Permisos',
    'Flight Recorder',
    'Las vistas del producto en vivo tienen la etiqueta separada LIVE READ ONLY.',
    'Saltar al contenido',
    'Navegación principal',
    'Idioma',
    'Demo en curso…',
    'Borrador de solicitud no confiable',
    'Ej.: reduce la posición si la pérdida diaria supera el límite…',
    'El texto no se envía ni lo interpreta un LLM. Usa /policies para validar una plantilla estructurada.',
    'RECHAZADO · SIN ACCIÓN',
    'SINTÉTICO · SIMULACIÓN',
    'OBSERVADO · SINTÉTICO',
    'PENDIENTE',
    'M05 · VISTA PREVIA DE EXPERIENCIA',
    'RECORRIDO GUIADO',
    'SEGURIDAD FAIL-CLOSED',
    'VISTA DE CONFIANZA SOLO LECTURA',
    'SOLO DEMO',
    'SIN AUTORIDAD',
    'SOLO BORRADOR',
    'LINAJE LOCAL DE FIXTURE',
    'TRAZA DEMO · LOCAL',
    'RESULTADO SIMULADO',
  ],
});

const scenarioIds = [
  'protection-story',
  'stale-source',
  'permission-revoked',
  'delegate-changed',
  'provider-degraded',
] as const satisfies readonly DemoScenarioId[];

export const scenarioNames = localizeRows(scenarioIds, {
  en: [
    'Protection story',
    'Stale source',
    'Permission revoked',
    'Delegate changed',
    'Provider degraded',
  ],
  'pt-BR': [
    'História de proteção',
    'Fonte desatualizada',
    'Permissão revogada',
    'Delegado alterado',
    'Provedor degradado',
  ],
  es: [
    'Historia de protección',
    'Fuente desactualizada',
    'Permiso revocado',
    'Delegado cambiado',
    'Proveedor degradado',
  ],
});

const reasonCodes = ['STALE', 'GRANT_REVOKED', 'DELEGATE_CHANGED', 'PROVIDER_DEGRADED'] as const;

export const scenarioReasons = localizeRows(reasonCodes, {
  en: [
    demoCopy.en.staleReason,
    demoCopy.en.revokedReason,
    demoCopy.en.delegateReason,
    demoCopy.en.degradedReason,
  ],
  'pt-BR': [
    demoCopy['pt-BR'].staleReason,
    demoCopy['pt-BR'].revokedReason,
    demoCopy['pt-BR'].delegateReason,
    demoCopy['pt-BR'].degradedReason,
  ],
  es: [
    demoCopy.es.staleReason,
    demoCopy.es.revokedReason,
    demoCopy.es.delegateReason,
    demoCopy.es.degradedReason,
  ],
});

export const phaseLabels = localizeRows(GUIDED_PHASES, {
  en: ['Context', 'Risk', 'Policy', 'Deterioration', 'Safety', 'Outcome', 'Evidence', 'Closeout'],
  'pt-BR': [
    'Contexto',
    'Risco',
    'Política',
    'Deterioração',
    'Segurança',
    'Resultado',
    'Evidência',
    'Encerramento',
  ],
  es: [
    'Contexto',
    'Riesgo',
    'Política',
    'Deterioro',
    'Seguridad',
    'Resultado',
    'Evidencia',
    'Cierre',
  ],
});
