import type { Locale } from '../../i18n.ts';

export const recordingCopy = {
  en: {
    eyebrow: 'M06 · VIDEO RECORDING MODE',
    intro: 'A recording-safe view built only from the accepted deterministic M05 fixture.',
    home: 'Guided demo',
    live: 'Live risk dashboard · READ ONLY',
    nav: 'Recording surfaces',
    risk: 'Risk Dashboard',
    policy: 'Policy Builder',
    recorder: 'Flight Recorder',
    riskTitle: 'Risk, with its source in view.',
    policyTitle: 'Bounded policy, readable before its JSON.',
    recorderTitle: 'A synthetic trace you can follow.',
    riskIntro: 'The displayed observations are deterministic fixture values, never provider data.',
    policyIntro: 'This human-readable preview and its JSON are display-only, not an active policy.',
    recorderIntro: 'Every stage below is synthetic narrative lineage, not persisted evidence.',
    fixture: 'Fixture provenance',
    source: 'M05 Guided Demo · protection-story',
    quality: 'Source state',
    exposure: 'Example exposure',
    account: 'Synthetic account',
    position: 'Synthetic position',
    market: 'Market',
    triggerState: 'Trigger state',
    unavailable: 'Unavailable, unproven',
    policySummary: 'Human-readable constraints',
    trigger: 'Trigger',
    action: 'Action',
    fraction: 'Maximum action fraction',
    notional: 'Maximum notional',
    slippage: 'Maximum slippage',
    marketPosition: 'Market / position',
    cooldown: 'Cooldown',
    expiry: 'Expiry',
    refusal: 'Refusal behavior',
    confirmation: 'Confirmation representation',
    json: 'Inspect structured display-only fixture',
    jsonNote: 'This local object is not accepted by the policy API or execution path.',
    lineage: 'Synthetic evidence lineage',
    explicit: 'No database write · no provider request · no wallet · no transaction · no receipt.',
    boundaries:
      'MAINNET EFFECT = HARD_BLOCKED · LIVE PERPL WRITES = BLOCKED · NERVA_EXECUTION_ENABLED=false',
  },
  'pt-BR': {
    eyebrow: 'M06 · MODO DE GRAVAÇÃO DE VÍDEO',
    intro:
      'Uma visualização segura para gravação, baseada somente na fixture determinística M05 aprovada.',
    home: 'Demo guiada',
    live: 'Painel de risco ao vivo · READ ONLY',
    nav: 'Telas para gravação',
    risk: 'Painel de risco',
    policy: 'Construtor de políticas',
    recorder: 'Flight Recorder',
    riskTitle: 'Risco com a origem visível.',
    policyTitle: 'Política limitada, legível antes do JSON.',
    recorderTitle: 'Uma trilha sintética que você pode acompanhar.',
    riskIntro:
      'As observações exibidas são valores determinísticos de fixture, nunca dados do provedor.',
    policyIntro:
      'Esta prévia legível e seu JSON são somente para exibição, não são uma política ativa.',
    recorderIntro: 'Cada etapa abaixo é uma narrativa sintética, não uma evidência persistida.',
    fixture: 'Proveniência da fixture',
    source: 'Demo guiada M05 · protection-story',
    quality: 'Estado da origem',
    exposure: 'Exposição de exemplo',
    account: 'Conta sintética',
    position: 'Posição sintética',
    market: 'Mercado',
    triggerState: 'Estado do gatilho',
    unavailable: 'Indisponível, não comprovado',
    policySummary: 'Limites em linguagem clara',
    trigger: 'Gatilho',
    action: 'Ação',
    fraction: 'Fração máxima da ação',
    notional: 'Notional máximo',
    slippage: 'Slippage máximo',
    marketPosition: 'Mercado / posição',
    cooldown: 'Intervalo de segurança',
    expiry: 'Expiração',
    refusal: 'Comportamento de recusa',
    confirmation: 'Representação da confirmação',
    json: 'Inspecionar fixture estruturada somente para exibição',
    jsonNote: 'Este objeto local não é aceito pela API de políticas nem pelo fluxo de execução.',
    lineage: 'Linhagem sintética de evidências',
    explicit:
      'Sem gravação no banco · sem chamada ao provedor · sem carteira · sem transação · sem recibo.',
    boundaries:
      'MAINNET EFFECT = HARD_BLOCKED · LIVE PERPL WRITES = BLOCKED · NERVA_EXECUTION_ENABLED=false',
  },
  es: {
    eyebrow: 'M06 · MODO DE GRABACIÓN DE VIDEO',
    intro: 'Una vista segura para grabar, basada solo en la fixture determinística M05 aprobada.',
    home: 'Demo guiada',
    live: 'Panel de riesgo en vivo · READ ONLY',
    nav: 'Vistas para grabación',
    risk: 'Panel de riesgo',
    policy: 'Constructor de políticas',
    recorder: 'Flight Recorder',
    riskTitle: 'Riesgo con su fuente a la vista.',
    policyTitle: 'Política limitada, legible antes del JSON.',
    recorderTitle: 'Una traza sintética que puedes seguir.',
    riskIntro:
      'Las observaciones mostradas son valores determinísticos de fixture, nunca datos del proveedor.',
    policyIntro: 'Esta vista legible y su JSON son solo para mostrar, no son una política activa.',
    recorderIntro: 'Cada etapa es una narrativa sintética, no evidencia persistida.',
    fixture: 'Procedencia de la fixture',
    source: 'Demo guiada M05 · protection-story',
    quality: 'Estado de la fuente',
    exposure: 'Exposición de ejemplo',
    account: 'Cuenta sintética',
    position: 'Posición sintética',
    market: 'Mercado',
    triggerState: 'Estado del disparador',
    unavailable: 'No disponible, no probado',
    policySummary: 'Límites en lenguaje claro',
    trigger: 'Disparador',
    action: 'Acción',
    fraction: 'Fracción máxima de acción',
    notional: 'Notional máximo',
    slippage: 'Slippage máximo',
    marketPosition: 'Mercado / posición',
    cooldown: 'Enfriamiento',
    expiry: 'Vencimiento',
    refusal: 'Comportamiento de rechazo',
    confirmation: 'Representación de confirmación',
    json: 'Inspeccionar fixture estructurada solo para mostrar',
    jsonNote:
      'Este objeto local no es aceptado por la API de políticas ni por el flujo de ejecución.',
    lineage: 'Linaje sintético de evidencia',
    explicit:
      'Sin escritura en base de datos · sin solicitud al proveedor · sin cartera · sin transacción · sin recibo.',
    boundaries:
      'MAINNET EFFECT = HARD_BLOCKED · LIVE PERPL WRITES = BLOCKED · NERVA_EXECUTION_ENABLED=false',
  },
} satisfies Record<Locale, Record<string, string>>;
