export const M05_POLICY_TEMPLATES = Object.freeze({
  boundedReduce: Object.freeze({
    schemaVersion: '0.1',
    policyId: 'm05-example-bounded-reduce',
    version: 1,
    createdByActorRef: 'example-operator',
    environment: 'TESTNET_DEMO',
    scope: {
      network: 'monad-testnet',
      protocolCapability: 'perpl-protective-v0',
      accountId: '1',
      positionId: '1',
      marketSelector: 'eth-perp',
    },
    triggers: [{ metric: 'POSITION_ADVERSE_MOVE_BPS', operator: 'GTE', thresholdBps: 800 }],
    actionIntent: { family: 'REDUCE_POSITION', maxActionFractionBps: 1000 },
    constraints: {
      maxActionFractionBps: 1000,
      maxReducibleQuantityScaled: '1000000',
      maxNotionalMicros: '5000000000',
      maxSlippageBps: 25,
      cooldownSeconds: 60,
      expiresAt: '2030-01-01T00:00:00.000Z',
      maxPlanAgeSeconds: 30,
      allowedProtocols: ['perpl-protective-v0'],
      allowedMarkets: ['eth-perp'],
      fallbackAction: 'NO_ACTION',
    },
    safetyBehavior: 'REFUSE',
    metadata: {
      label: 'Example: bounded position reduction',
      description: 'A non-authoritative M05 template used for validation only.',
    },
  }),
  closeOnDrawdown: Object.freeze({
    schemaVersion: '0.1',
    policyId: 'm05-example-close-on-drawdown',
    version: 1,
    createdByActorRef: 'example-operator',
    environment: 'TESTNET_DEMO',
    scope: {
      network: 'monad-testnet',
      protocolCapability: 'perpl-protective-v0',
      accountId: '1',
      positionId: '1',
      marketSelector: 'eth-perp',
    },
    triggers: [{ metric: 'PORTFOLIO_DRAWDOWN_BPS', operator: 'GTE', thresholdBps: 1000 }],
    actionIntent: { family: 'CLOSE_POSITION', maxActionFractionBps: 10000 },
    constraints: {
      maxActionFractionBps: 10000,
      maxReducibleQuantityScaled: '1000000',
      maxNotionalMicros: '5000000000',
      maxSlippageBps: 20,
      cooldownSeconds: 120,
      expiresAt: '2030-01-01T00:00:00.000Z',
      maxPlanAgeSeconds: 20,
      allowedProtocols: ['perpl-protective-v0'],
      allowedMarkets: ['eth-perp'],
      fallbackAction: 'NO_ACTION',
    },
    safetyBehavior: 'REFUSE',
    metadata: {
      label: 'Example: close on drawdown',
      description: 'A non-authoritative M05 template used for validation only.',
    },
  }),
} as const);
